## Github action to execute a qa-tests when a pull request is created

name: run-qa-tests

on: pull_request

env:
  JENKINS_HOST: https://jenkins.hostname.com

jobs:
  launch_jenkins_deploy:
    name: Launch jenkins deploy-ENV job
    runs-on: ubuntu-latest
    steps:
      -
        name: Select branch where qa tests will be run
        run: echo "JENKINS_PARAMS=branch=${{ github.head_ref }}" >> $GITHUB_ENV
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@v1.2
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_HOST: ${{ env.JENKINS_HOST }}
          JENKINS_JOB: ${{ secrets.JENKINS_JOB }}
          JENKINS_PARAMS: ${{ env.JENKINS_PARAMS }}
